### ISSUE TITLE
第五章の問題について

### ISSUE THREAD

**Issue by makinzm** [recsyslab/recsys-python#14]
いつもこちらの問題集を楽しく解かせていただいております。
誠にありがとうございます。

本日は,第五章の問題が被っている可能性があり疑問に感じたため,ご報告させていただきます。
（該当リンク : https://recsyslab.github.io/recsys-python/ja/chap05.html）

『ピアソンの相関係数』の定義と『平均中心化評価値行列に基づくピアソンの相関係数』の定義が
全く同じであると考えれます。
そのため,問4,5,6と問1,2,3のどちらかを採用すれば良いと考えられますが,いかがでしょうか。

こちらに関してご回答いただけますと幸いです🙇‍♂️

**Comment by okukenta** [comment]
recsys-pythonをご利用頂き有難うございます。

第5章の問01-03と問04-06ですが、問題の意図としては前者が評価値行列`R`をそのまま使ってピアソンの相関係数を計算するのに対し、後者は平均中心化評価値行列`R2`を使って計算するというものです。`R2`は準備のコードで用意しているものです。一つの式の中で平均中心化を行うか、事前に平均中心化しておくかの違いだけですので、本質的には両者とも同等になります。

出力結果はいずれも同じですので、以降の問題はどちらの結果を採用頂いても違いはありません。

問04-06については「`R2`を参照し、」という文言を追記しました。

**Comment by makinzm** [comment]
承知いたしました。ご回答いただきありがとうございます。
