### ISSUE TITLE
第8章 評価値行列の次元削減 主成分得点

### ISSUE THREAD

**Issue by MTDTMFH** [recsyslab/recsys-python#18]
<img width="644" alt="Screen Shot 2022-10-27 at 11 33 58" src="https://user-images.githubusercontent.com/32162131/198177292-8fd374ac-12f6-4427-84f9-88dba7115367.png">

v_ikではないのでしょうか？数学に詳しいものではないので、誤認でしたら申し訳ございませんが、列は第k主成分だと思います。

**Comment by okukenta** [comment]
ご質問ありがとうございます。確かに、行列Vのi行目、k列目の成分と考えると、v_ikとした方が自然かもしれません。ただ、この問題は元の教科書から抜粋したもので、元々は、行列Vを[\bm{v}_1, \bm{v}_2]と二つの縦ベクトルを並べる形で表しています。そして、各ベクトルの要素として、ベクトル\bm{v}_kのi番目の要素をv_k,iと表現しているという流れがあります。ご指摘はごもっともですが、ここは教科書に合わせておきたいので、v_k,iのままにさせてください。

**Comment by MTDTMFH** [comment]
承知いたしました！また、早急にご返信ありがとうございました。githubの演習問題は大変参考になっておりますので、ご掲示いただいて感謝しております。
