### ISSUE TITLE
表記ミス？　第3章問06

### ISSUE THREAD

**Issue by yoyoyo-yo** [recsyslab/recsys-python#7]
大変ためになる問題集をありがとうございます。
第3章問06が下記のようになっていますが、おそらく消す箇所を誤っていないかと思われます。（答えが見えてしまっているのかと、、）

(答えになるので編集済み)

**Comment by okukenta** [comment]
ご利用頂き有難うございます。ご指摘の通りですので、修正いたしました。有難うございました。
